name: Medusa CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG="rameshxt/medusa-backend:v1.0.${GITHUB_RUN_NUMBER}"
          echo "Building image with tag: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .

      - name: Update ECS Image Tag in ecs.tf
        run: |
          bash image-updater.sh "rameshxt/medusa-backend:v1.0.${GITHUB_RUN_NUMBER}"

      - name: Push Docker Image to Docker Hub
        run: |
          docker push "rameshxt/medusa-backend:v1.0.${GITHUB_RUN_NUMBER}"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to ECS using Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
