name: Medusa CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG="rameshxt/medusa-backend:v1.0.${ github.sha }"
          docker build -t $IMAGE_TAG .

      - name: Update ECS Image Tag in ecs.tf
        run: |
          bash /medusa-store/image-updater.sh "rameshxt/medusa-backend:v1.0.${{ github.sha }}"

      - name: Push Docker Image to Docker Hub
        run: |
          docker push "rameshxt/medusa-backend:v1.0.${ github.sha }"

      - name: Deploy to ECS using Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
